before_install: 
  - docker pull electronuserland/builder
  - sudo apt install libdbus-1-3
  - ./fetch.sh > fetchOutput.txt
notifications:
  email: false
matrix:
  exclude:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  include:
    - os: linux
      services: docker
      language: generic

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

script:
  - /bin/bash -c "./build.sh > buildOutput.txt"

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file:
    - ./../build/*.deb
    - ./../build/*.AppImage
  skip_cleanup: true
  draft: true
