notifications:
  email: false
  
matrix:
  include:
    - os: linux
      services: docker
      language: generic
      
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
  
cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  
before_install: 
  - docker pull electronuserland/builder
  - ./fetch.sh > fetchOutput.txt
  -  chmod -R +x /home/travis/build/scratux/scratux/src/node_modules/7zip-bin
  
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  
script:
  - /bin/bash -c "./build.sh > buildOutput.txt"
  
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file:
    - ./../build/*.deb
    - ./../build/*.AppImage
  skip_cleanup: true
  draft: true
