notifications:
  email: false
  
matrix:
  include:
    - os: linux
      services: docker
      language: generic
      
before_install: 
  - docker pull electronuserland/builder
  - sudo apt install xz-utils
  - sudo apt install libdbus-1-3
  - sudo apt-get install --no-install-recommends -y gcc-multilib g++-multilib
  - sudo apt-get install --no-install-recommends -y rpm
  - nohup ./fetch.sh > /dev/null 2>&1 &
  
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  
script:
  - nohup ./build.sh > /dev/null 2>&1 &
  
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file:
    - ./../build/*.deb
    - ./../build/*.AppImage
  skip_cleanup: true
  draft: true
